Q3. Load the data from wine dataset. Check whether all attributes are standardized or not (mean is 0 and standard deviation is 1). 

If not, standardize the attributes. Do the same with Iris dataset.

In [1]:
import pandas as pd
import numpy as np
import sklearn as skl
from sklearn import preprocessing

In [2]:
df = pd.read_csv("wine.csv")
df

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2       1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3       1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4       1    13.24        2.59  2.87  21.0  118     2.80        2.69   
..    ...      ...         ...   ...   ...  ...      ...         ...   
173     3    13.71        5.65  2.45  20.5   95     1.68        0.61   
174     3    13.40        3.91  2.48  23.0  102     1.80        0.75   
175     3    13.27        4.28  2.26  20.0  120     1.59        0.69   
176     3    13.17        2.59  2.37  20.0  120     1.65        0.68   
177     3    14.13        4.10  2.74  24.5   96     2.05        0.76   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                    0.28     2.29       5.64  1.04  3.92     1065  
1                    0.26     1.28       4.38  1.05  3.40     1050  
2                    0.30     2.81       5.68  1.03  3.17     1185  
3                    0.24     2.18       7.80  0.86  3.45     1480  
4                    0.39     1.82       4.32  1.04  2.93      735  
..                    ...      ...        ...   ...   ...      ...  
173                  0.52     1.06       7.70  0.64  1.74      740  
174                  0.43     1.41       7.30  0.70  1.56      750  
175                  0.43     1.35      10.20  0.59  1.56      835  
176                  0.53     1.46       9.30  0.60  1.62      840  
177                  0.56     1.35       9.20  0.61  1.60      560  

[178 rows x 14 columns]

In [3]:
calc_mean = df.mean(axis=0)
calc_mean

Wine                      1.938202
Alcohol                  13.000618
Malic.acid                2.336348
Ash                       2.366517
Acl                      19.494944
Mg                       99.741573
Phenols                   2.295112
Flavanoids                2.029270
Nonflavanoid.phenols      0.361854
Proanth                   1.590899
Color.int                 5.058090
Hue                       0.957449
OD                        2.611685
Proline                 746.893258
dtype: float64

In [4]:
calc_std = df.std(axis=0)
calc_std

Wine                      0.775035
Alcohol                   0.811827
Malic.acid                1.117146
Ash                       0.274344
Acl                       3.339564
Mg                       14.282484
Phenols                   0.625851
Flavanoids                0.998859
Nonflavanoid.phenols      0.124453
Proanth                   0.572359
Color.int                 2.318286
Hue                       0.228572
OD                        0.709990
Proline                 314.907474
dtype: float64

In [5]:
df = preprocessing.scale(df,axis=0)

In [6]:
df.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
df.mean(axis=0)

array([ 1.59672525e-16, -8.38280756e-16, -1.19754394e-16, -8.37033314e-16,
       -3.99181312e-17, -3.99181312e-17,  0.00000000e+00, -3.99181312e-16,
        3.59263181e-16, -1.19754394e-16,  2.49488320e-17,  1.99590656e-16,
        3.19345050e-16, -1.59672525e-16])

In [11]:
from sklearn.datasets import load_iris
data = load_iris()
X_data = data.data
target = data.target

# Here standard deviation is 1 and mean near to 0(for iris dataset)

In [12]:
df_iris = preprocessing.scale(X_data,axis=0)
df_iris.std(axis=0)

array([1., 1., 1., 1.])

In [13]:
df_iris.mean(axis=0)

array([-1.69031455e-15, -1.84297022e-15, -1.69864123e-15, -1.40924309e-15])